[features]
seeds = false
skip-lint = false
[programs.localnet]
piersol = "BFyTZKQiRPnk8AkBEfD1mhm5ZGuq46GWXg5wbFAYPzPx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/pier/solanapier/hk"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
