[features]
seeds = false
skip-lint = false
[programs.localnet]
piersol = "23DXeZpr2ZqvTa2eqFtQmzrv8sm4CG4D5RS8bM5WVQnw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/pier/solanapier/hk"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
